### ISSUE TITLE
Circular Dependency Between Sys.hh and Workload.hh

### ISSUE THREAD

**Issue by steinbrecher** [astra-sim/astra-sim#10]
Notably, Sys.hh imports Workload.hh [on line 530](https://github.com/astra-sim/astra-sim/blob/8d1d2cc31b72d4461ff7cc91092ed6b811950b39/astra-sim/system/Sys.hh#L530). Workload.hh also imports Sys.hh at the top of the file, but a one-way dependency is fine, and a mid-file import is a much worse thing from a readability / usability perspective than the top of file. 

This is a strong sign that the two files need to be broken into smaller pieces -- header dependencies should form a DAG, not a graph with cycles. 

Are there any classes that have mutual dependencies in such a way that we can't solve this with forward declarations and separate header/source files?

**Comment by steinbrecher** [comment]
Let's use some "in-person" meeting time to discuss how to move forward on this -- the above issue as described isn't completely scoped and I have some thoughts on how to make it easier.

**Comment by rashidi1saeed** [comment]
> Notably, Sys.hh imports Workload.hh [on line 530](https://github.com/astra-sim/astra-sim/blob/8d1d2cc31b72d4461ff7cc91092ed6b811950b39/astra-sim/system/Sys.hh#L530). Workload.hh also imports Sys.hh at the top of the file, but a one-way dependency is fine, and a mid-file import is a much worse thing from a readability / usability perspective than the top of file.
> 
> This is a strong sign that the two files need to be broken into smaller pieces -- header dependencies should form a DAG, not a graph with cycles.
> 
> Are there any classes that have mutual dependencies in such a way that we can't solve this with forward declarations and separate header/source files?

You are right. Logically, the workload layer should only include the sys header files and there is no need for sys layer to know about the workload. But the issue is the way we instantiate during the initialization. Because our way is creating the layers from the bottom up, this means that during initialization, net layer creates sys layer, and then sys layer creates the workload layer. Hence, the sys layer needs to include the workload header file.
