### ISSUE TITLE
Have I performed  proper steps to convert PyTorch traces?

### ISSUE THREAD

**Issue by bluegrey23** [astra-sim/astra-sim#114]
Hello. 
I could run astra-sim as steps in Readme, i.e. use chakra ETconverter to convert ASTRA-sim 1.0 text input files into Chakra traces and run the simulation process with AnalyticalAstra. However, an error occurred when I tried to converte PyTorch traces to Chakra traces.
The error is 
`ERROR [09/23/2023 05:35:41 PM] 'nodes' `
My command is 
`python3 -m et_converter.et_converter     --input_type PyTorch     --input_filename ../../../trace.json     --output_filename myout   --num_npus 64     --num_dims 1     --num_passes 1 --default_simulated_run_time 100`

And I utilized the following code snippet to generate PyTorch trace.
```
with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
    model(inputs)
prof.export_chrome_trace("trace.json")
```

I wonder if there any error in my process,  and appreciate any suggestion.

**Comment by TaekyungHeo** [comment]
Thank you for reaching out and providing detailed information about the issue you encountered.

I'd like to inform you that the et_converter for PyTorch traces is currently under active development. It's not fully mature yet, but we are aware of its limitations. We are working diligently on it and aim to release a more stable version within the next 2-3 weeks.

Regarding the method you've used to generate the PyTorch trace, it seems there is a discrepancy. Instead of using the chrome profiler, you should be utilizing the ExecutionGraphObserver within PyTorch. Additionally, you should be collecting kineto traces. In addition, you should use [trace_link.py](https://github.com/facebookresearch/param/blob/main/train/compute/python/tools/trace_link.py) that will assist in merging execution traces with kineto traces. The execution traces provide information about the operators and their dependencies, while the kineto traces give details about the duration of the operators.

Rest assured, we'll release these tools along with detailed instructions in the upcoming 2-3 weeks.

We appreciate your patience and understanding. In the meantime, if you have any further questions or face any other issues, please don't hesitate to let us know.

**Comment by bluegrey23** [comment]
Great thanks for your information，  and eagerly await the release in two or three weeks.Thanks,Yuan------------------ 原始邮件 ------------------发件人：Taekyung Heo ***@***.***"时　间：2023/09/25 11:28:36 周一收件人：astra-simastra-sim ***@***.***"抄送人：bluegrey23 ***@***.***", Author ***@***.***"主　题：Re: [astra-sim/astra-sim] Have I performed  proper steps to convert PyTorch traces? (Issue #114)Thank you for reaching out and providing detailed information about the issue you encountered.I'd like to inform you that the et_converter for PyTorch traces is currently under active development. It's not fully mature yet, but we are aware of its limitations. We are working diligently on it and aim to release a more stable version within the next 2-3 weeks.Regarding the method you've used to generate the PyTorch trace, it seems there is a discrepancy. Instead of using the chrome profiler, you should be utilizing the ExecutionGraphObserver within PyTorch. Additionally, you should be collecting kineto traces. In addition, you should use trace_link.py that will assist in merging execution traces with kineto traces. The execution traces provide information about the operators and their dependencies, while the kineto traces give details about the duration of the operators.Rest assured, we'll release these tools along with detailed instructions in the upcoming 2-3 weeks.We appreciate your patience and understanding. In the meantime, if you have any further questions or face any other issues, please don't hesitate to let us know.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
