### ISSUE TITLE
Unable to clone the Astrasim repo with the --recurse-submodules command provided in the Readme.

### ISSUE THREAD

**Issue by byungchoi103** [astra-sim/astra-sim#124]
Hi, I'm trying to clone the Astrasim repo following the commands provided in the Readme section. However, I'm not able to clone the repo along with its submodules. I'm getting the following error:

```
$: ~/git_repos$ git clone --recurse-submodules https://github.com/astra-sim/astra-sim.git
Cloning into 'astra-sim'...
remote: Enumerating objects: 4451, done.
remote: Counting objects: 100% (963/963), done.
remote: Compressing objects: 100% (317/317), done.
remote: Total 4451 (delta 676), reused 778 (delta 620), pack-reused 3488
Receiving objects: 100% (4451/4451), 1.94 MiB | 8.39 MiB/s, done.
Resolving deltas: 100% (2726/2726), done.
Submodule 'extern/graph_frontend/chakra' (git@github.com:mlcommons/chakra.git) registered for path 'extern/graph_frontend/chakra'
Submodule 'extern/network_backend/analytical' (git@github.com:astra-sim/astra-network-analytical.git) registered for path 'extern/network_backend/analytical'
Submodule 'extern/network_backend/garnet/gem5_astra' (git@github.com:astra-sim/astra-network-garnet.git) registered for path 'extern/network_backend/garnet/gem5_astra'
Submodule 'extern/network_backend/ns3' (https://github.com/astra-sim/astra-network-ns3.git) registered for path 'extern/network_backend/ns3'
Submodule 'extern/memory_backend/analytical' (git@github.com:astra-sim/astra-memory-analytical.git) registered for path 'extern/remote_memory_backend/analytical'
Cloning into '/home/c.michael103/git_repos/astra-sim/extern/graph_frontend/chakra'...






sss_ssh_knownhostsproxy: connect to host github.com port 22: Connection timed out
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mlcommons/chakra.git' into submodule path '/home/c.michael103/git_repos/astra-sim/extern/graph_frontend/chakra' failed
Failed to clone 'extern/graph_frontend/chakra'. Retry scheduled
Cloning into '/home/c.michael103/git_repos/astra-sim/extern/network_backend/analytical'...

```

I've also added my id_rsa.pub key into the github ssh key. Yet, I'm not able to clone the repo along with all its submodules as specified in the README file. Please let me know if I'm missing anything here. Thank!
- Michael C.

**Comment by TaekyungHeo** [comment]
Hello, @byungchoi103. Does the following command work?
```
ssh -T git@github.com
```
It should say something like "Hi [YourUsername]! You've successfully authenticated...".

**Comment by byungchoi103** [comment]
>:~/git_repos$ ssh -T git@github.com

sss_ssh_knownhostsproxy: connect to host github.com port 22: Connection timed out
kex_exchange_identification: Connection closed by remote host

Looks like it doesn't work. 
What could be an issue?

**Comment by TaekyungHeo** [comment]
Thank you for providing the details. Let's try to narrow down the potential causes:

**1. SSH Key Registration:**
* Please ensure that your SSH key has been added to your GitHub account.
To check your currently added SSH keys: cat ~/.ssh/id_rsa.pub and see if this public key matches what's in your GitHub account. If not, you'll need to [add it to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

**2. Network Restrictions:**
* Are you accessing GitHub from a corporate or institutional network? It's possible that SSH connections over port 22 are blocked by a firewall or other network restrictions.
* If you have the capability, you might try connecting to GitHub via another network, such as a home network or through a mobile hotspot, just to check if the issue persists.

Given the error, it's unlikely this is an issue on GitHub's end or due to specific repository settings. The primary focus here should be on the local SSH setup and potential network restrictions.

Please verify the above and let us know. If the problem persists, we can explore further troubleshooting steps.

**Comment by TaekyungHeo** [comment]
Let me close this issue. Please reopen this issue if the problem persists.

**Comment by byungchoi103** [comment]
I am still getting following errors.
$ ssh -T git@github.com
sss_ssh_knownhostsproxy: connect to host github.com port 22: Connection timed out
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

Actually, I realized that I am having problem with "$ git clone --recurse-submodules git@github.com:astra-sim/astra-sim.git
$ cd ./astra-sim/" command. Some reason, I can't download submodules. It hangs while git cloning is going on. As you know those submodule of 4 sub-directories under extern, I can't download. 
I did git clone submodules independently and located on those 4 sub-directories. Unfortunately, I can't build it - something is missing if I git clone independently.

Please let me know what could be an issue and solutions. Thanks in advance!

**Comment by byungchoi103** [comment]
I found that when I try "Download Zip" on window, I see there is no submodule source code in the sub-directories under extern too.

**Comment by TaekyungHeo** [comment]
Thank you for providing more information. Could you please ensure that you have registered your public key with GitHub correctly? The failure you're encountering when you run `ssh -T git@github.com` suggests there's an authentication or connection issue with GitHub, which isn't specific to our repository.
