### ISSUE TITLE
Questions about communication time please!

### ISSUE THREAD

**Issue by eric2023h** [astra-sim/astra-sim#150]
Hi,

Thanks tons for this amazing tool! Here are some questions coming up when we are dealing with DL model training simulations.

1) Astra-sim 1.0:
To the best of our knowledge, the network system settings involved in Astra-sim 1.0 is homogeneous (latency regarding different dimensions are the same), so the communication time from simulation results of, (M, N) and (N*M), different units count should be similar. But experiments showed that actually there is huge gap between the two results, i.e., (2, 8) and (8, 2). How does that happen and why?

**example:
dimensions-count: 2
topologies-per-dim: ring, ring
links-count: 2, 2
units-count 2, 8 or 8, 2
link-latency: 1, 1
link-bandwidth: 200, 200**

2) Astra-sim 2.0:
May we know what it means by "... finished in ... cycles" from the simulation result exactly? Is there any chance we can calculate the communication time out of the result, like it does in Astra-sim 1.0?

Thank you so much for this helpful tool again and look forward to your instruction!

**Comment by TaekyungHeo** [comment]
Hello @eric2023h,

For your first question, I've reached out to @willjwon, who is best suited to provide an in-depth response. He should be responding shortly.

Regarding your second question, a detailed explanation is available in our discussion at https://github.com/astra-sim/astra-sim/issues/148.

**Comment by eric2023h** [comment]
> Hello @eric2023h,
> 
> For your first question, I've reached out to @willjwon, who is best suited to provide an in-depth response. He should be responding shortly.
> 
> Regarding your second question, a detailed explanation is available in our discussion at #148.

couldn't be more grateful!

**Comment by willjwon** [comment]
Hi @eric2023h,

First of all, please excuse my belated response! Thanks so much for your interest in ASTRA-sim framework.

Regarding your questions:
1. ASTRA-sim 1.0
- Please note that ASTRA-sim 1.0 can model heterogeneous network topologies (by this term, I mean a multi-dimensional network whose link latency or BW differs across dimensions). For example, you may set the link BW as `link-bandwidth: [200, 50]` to model a heterogeneous network whose 1st Dim BW is 200 GB/s, whereas the 2nd Dim BW is 50 GB/s, only a quarter of the first dimension.
- By the given configuration, you're running a hierarchical All-Reduce. In this scheme, you first run Reduce-Scatter on 1st Dim, then All-Reduce (i.e., Reduce-Scatter + All-Gather) on 2nd Dim, then finally Run All-Gather on 1st Dim (please refer to the Figure 1(b) of paper [this paper](https://arxiv.org/abs/2303.14006) for more details).
  - Let's say, you have (8, 2) network topology (thus 8 × 2 = 16 NPUs) and you're running an 1 GB (= 1024 MB) All-Reduce. Because of the Reduce-Scatter on the 1st Dim, the message to be processed by the 2nd Dim reduces to 128 MB (= 1024 MB / 8 NPUs). Such 128 MB message should be communicated across 2 NPUs in the 2nd network Dim.
  - If you have (2, 8) network (again the same 16 NPUs), however, the chunk size of the 2nd Dim is now 512 MB (= 1024 MB / 2 NPUs), which should be communicated across 8 NPUs in the 2nd network Dim.
- Therefore, even if both have the same 16 NPUs, their implications in communications are quite different. Ultimately, this is from the fact that we're running hierarchical All-Reduce, where we run Reduce-Scatter in lower dimensions and actively reduce messages to be processed by the next dimension.

2. Currently, you can assume each cycle's granularity is in nanoseconds (ns), so if you see `... finished in 123 cycles`, let's say, this means the simulation has ended at time `123 ns`. We're currently improving ASTRA-sim 2.0 to report more useful data in much finer granularity as you've brought up, including those logs in ASTRA-sim 1.0.

Hope this can help, and please let us know if you have any follow-up questions.

**Comment by jeongyoonm** [comment]
Hi @willjwon, 
Thanks for the amazing tool. 
> We're currently improving ASTRA-sim 2.0 to report more useful data in much finer granularity as you've brought up, including those logs in ASTRA-sim 1.0.
I wonder if you have any updates/plans for this. It would be great to have such features.
Thanks,
Jeongyoon

**Comment by willjwon** [comment]
@jeongyoonm Thanks for your interest in the ASTRA-sim framework. Answering your question:
- The work is still in-progress, with some updates first coming to the logging system (as exemplified in this PR: https://github.com/astra-sim/astra-sim/pull/151)
- We plan to work on the results system such as result breakdown, but unfortunately, the work is not available at the moment.

I'm closing this issue for now, please resubmit any subsequent issues if there's more questions.
