### ISSUE TITLE
 Simulate more npus with fewer traces of npus.

### ISSUE THREAD

**Issue by DylanSoren** [astra-sim/astra-sim#168]
Now I have collected 4 NPU traces, obtained Chakra format data through link and converter, and used these data as the workload layer parameters of analytical or ns3. But if I want to simulate more npus (e.g. 8, 16, 64) just from the traces of these 4 npus, can the current emulator do the job, and if so, how should I do it?

**Comment by jinsun-yoo** [comment]
Hi @DylanSoren , we currently don't have ways to 'duplicate' traces from 4 NPUs to 8 NPUs. However, if you could provide a detailed explanation, we could provide pointers to synthetically generating a similar trace across 8NPUs.

I'm closing this issue due to staleness, but please feel free to reopen this issue if you want to move forward with the direction above.

**Comment by dageita** [comment]
> Hi @DylanSoren , we currently don't have ways to 'duplicate' traces from 4 NPUs to 8 NPUs. However, if you could provide a detailed explanation, we could provide pointers to synthetically generating a similar trace across 8NPUs.
> 
> I'm closing this issue due to staleness, but please feel free to reopen this issue if you want to move forward with the direction above.
Please tell me how to  synthetically generating traces.
