### ISSUE TITLE
Some questions when generating workload input files

### ISSUE THREAD

**Issue by kkenshin1** [astra-sim/astra-sim#45]
Hi. 

I use `/scripts/workload_generators/gen_astrasim_workload_input.py` script to generate workload input files. I found that the “forward pass compute time” and “input grad compute time” in the output file are the same, but it is different in `inputs/workload/Resnet50_DataParallel.txt`.

Moreover, "delay per entire weight/input/output update after the collective is finished" of all lines in tthe output file are all "100", but it is also different in `inputs/workload/Resnet50_DataParallel.txt`. In `gen_astrasim_workload_input.py`, this parameter is fixed at 100.

Here are my command and output result.

```
$ python3 gen_astrasim_workload_input.py \
  --datatype_size=2 \
  --mnk=mnk_inputs/example.csv \
  --num_npus=16 \
  --num_packages=2 \
  --output_file=../../inputs/workload/example_DATA.txt \
  --parallel=DATA \
  --run_name=example \
  --scalesim_config=../../extern/compute/SCALE-Sim/configs/google.cfg \
  --scalesim_path=../../extern/compute/SCALE-Sim
```

MLP_Bottom_0|-1|1659|NONE|0|1659|NONE|0|1277|ALLREDUCE|131072|100|DATA
:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:
MLP_Bottom_1|-1|3319|NONE|0| 3319|NONE|0|2555|ALLREDUCE|524288|100|DATA
MLP_Bottom_2|-1|3319|NONE|0| 3319|NONE|0| 2555|ALLREDUCE|524288|100|DATA
MLP_Bottom_3|-1|1659|NONE|0| 1659|NONE|0|1563|ALLREDUCE|16384|100|DATA
MLP_Top_0|-1| 6639|NONE|0|6639|NONE|0|5111|ALLREDUCE|1048576|100|DATA
MLP_Top_1|-1| 3319|NONE|0| 3319|NONE|0|2555|ALLREDUCE|524288|100|DATA
MLP_Top_2|-1| 3319|NONE|0| 3319|NONE|0| 2555|ALLREDUCE|524288|100|DATA

So, What should I do to generate a input file correctly?

Thanks.

**Comment by rashidi1saeed** [comment]
Hi @kkenshin1,
Thanks for reaching us,
Not all sample workload input files are generated by the workload generator. Some of those files are generated either by other simulators or real measurements. Hence, you may see some differences between workload generator output files and other sample workload files. Our workload generator uses SCALE-SIM as the backend for determining the compute times, and since the forward-pass, weight-gradient, and input-gradients have similar #FLOPs, it is very likely SCALE-SIM reports similar compute times for those layers. 

Also one side note, Given your layer names, I guess you are generating DLRM workload input files. If this is the case, please follow the format of the DLRM workload input file. The workload generator does not natively support generating DLRM workload input files, but you can generate the compute times of the  MLP layer using the workload generator, and then add the embedding layer as the first layer in the workload input file.  Also, due to its complex nature  DLRM workload input file receives one more metadata number in its first line:

[https://github.com/astra-sim/astra-sim/blob/master/inputs/workload/DLRM_HybridParallel.txt#L1](url)

This is the number that indicates the last bottom MLP layer. In the above example, this number is 4, because the 4'th layer is the last bottom MLP (assuming layer indexing starts from 0). Basically, we require this metadata since we want to know when to wait for embedding communication in forwarding pass and when issuing embedding gradient communication in the backdrop. You can add this metadata to your final DLRM workload input file. Also, since you are adding the embedding layer manually, you should update the total number of layers (line 2) in the final workload input file.

**Comment by kkenshin1** [comment]
Hi, @rashidi1saeed , well I got it. Thanks for your reply.
