### ISSUE TITLE
The difference between zero_latency_packets and non_zero_latency_packets

### ISSUE THREAD

**Issue by xiangchenwu** [astra-sim/astra-sim#72]
I don't know exactly what zero_latency_packets and non_zero_latency_packets mean.
What are the types of ‘MA’ in the NPU_to_MA?
Whether there are NPU_to_NPU and MA_to_MA transfers?
What is the meaning of remained_packets_per_max_count and max_count?
Thanks in advance.

**Comment by TaekyungHeo** [comment]
Q1. I don't know exactly what zero_latency_packets and non_zero_latency_packets mean.
These variables are associated with the ring collective communication implementation. Multiple messages are transferred from one node to another during this process. The first message is referred to as a zero-latency packet because it doesn't necessitate reduction. Subsequent messages are termed non-zero-latency packets as they require reduction upon receipt.

Q2. What are the types of ‘MA’ in the NPU_to_MA?
"MA" stands for Messaging Agent. It can either be a NIC or an NVLink SERDES.

Q3. Are there NPU_to_NPU and MA_to_MA transfers?
No, only NPU_to_MA and MA_to_NPU transfers exist.

Q4. What is the meaning of remained_packets_per_max_count and max_count?
Both of these variables pertain to the ring algorithm implementation in ASTRA-sim.
* max_count: It denotes the maximum number of messages that can be transferred within the system. The count is based on the number of nodes. For example, if there are four nodes, then the max_count is set to four.
* remained_packets_per_max_count: This counter monitors the number of packets left to be dispatched. It decreases as packets are sent to the network.
