### ISSUE TITLE
A problem about some streams unfinished when running astra-sim1.0 with ns3 

### ISSUE THREAD

**Issue by SallyChangLiu** [astra-sim/astra-sim#92]
> When running astra-sim1.0 with ns3 as the network backend, I found that some traffic on certain nodes was not scheduled for execution when the program ended. I discovered this issue by observing that the **stream_inject** and **stream_finished** parameters in the sys object were not equal upon program exit. 

> After analysis, it was found that when the traffic sent by src to dst was received, the corresponding task was searched for in the **expeRecvHash** map to schedule the execution of the callback function after successful reception of the traffic. However, if the task of sending traffic from src to dst had not been registered in the map yet, the asynchrony between the completion of traffic and the execution of the callback function would cause ns3 to finish executing the event list and exit the entire program, while traffic in astra-sim still remained unscheduled and not sent.

> Do you have a solution for this? I think that when sending traffic using ns3, the corresponding task should be registered in the map. When this stream is successfully received, the corresponding task can be found in the map and executed directly. However, this would require modifying the logic of astra-sim, which may have an impact on other network backends such as analytical. I hope to hear your response and thank you very much.

**Comment by taekyounghan** [comment]
Hi Sally
After seeing your question, I wondered if the problem I was experiencing was related to this.
I'm a Newbie on this simulator.

I'm having exactly the same problem as the issue below.
https://github.com/astra-sim/astra-sim/issues/77

Are you experiencing this error, too?

If you solved it, could you share the method?

A little advice would be of great help.

**Comment by SallyChangLiu** [comment]
corrupted size vs. prev_size in fastbins
Program received signal SIGABRT, Aborted.

I read your issue. I have seen this problem.My solution is to refactor the definition and declaration of the global variable **nodeHash** in extern/network_backend/ns3-interface/simulation/src/point-to-point/model/qbb-net-device.cc and extern/network_backend/ns3-interface/simulation/src/applications/model/rdma-client.cc. I move the definition of nodeHash into workerQueue.cc and the declaration of nodeHash into workerQueue.h, after moving those global
 variables I saved this problem. Hope my solution helps you！

**Comment by taekyounghan** [comment]
Hello. I think the point you found is the root cause of the error. Thanks for your solution. However, I was also able to eliminate errors by modifying the compiler version. I think it'd be good to refer to it.  https://github.com/astra-sim/astra-sim/issues/77#issuecomment-1696719610

**Comment by jinsun-yoo** [comment]
Hi @SallyChangLiu, apologies for the late reply. We tried to reproduce the issue, but was unable to do so. Would you be able to share the following files? If they are the same as provided in the repo, please let me know!
- `astra-sim/network_frontend/ns3.AstraSimNetwork.cc` file
- Workload & System input you used, which reside under `inputs/system` `inputs/workload`
- `extern/network_backend/ns3-interface/simulation/mix/config.txt` and the corresponding topology file. 

As for the fix you suggested, the change itself wouldn't be difficult. `sim_recv` using `expeRecvHashMap`, etc. is an NS3-specific implementation of the network API. Other implementation of the network API (i.e. sim_recv function) track collective finished in a different manner.  We would have to check if there are any other unexpected side effects, though.

**Comment by SallyChangLiu** [comment]
- In the astra-sim/network_frontend/ns3/AstraSimNetwork.cc I used a 2D topology and the workload file is Resnet50_DataParallel.txt  located in the inputs/workload directory. (I also encountered the same problem when using Resnet50_DataParallel.txt) The statement for configuring the network topology and workload in AstraSimNetwork.cc is:

> std::vector<std::vector<int>> physical_dims {
>   { 8, 4 }
> };
> std::vector<string> workloads {
>   "Resnet50_DataParallel.txt"
> };

- I have configured the system according to the instructions in the asplos2023/exercise_2/inputs/system/dgx2.txt file, which content is as follows:

> scheduling-policy: LIFO
> endpoint-delay: 10
> active-chunks-per-dimension: 1
> preferred-dataset-splits: 4
> boost-mode: 0
> all-reduce-implementation: halvingDoubling_halvingDoubling
> all-gather-implementation: halvingDoubling_halvingDoubling
> reduce-scatter-implementation: halvingDoubling_halvingDoubling
> all-to-all-implementation: direct_direct
> collective-optimization: localBWAware

- I did not modify other contents of the file extern/network_backend/ns3-interface/simulation/mix/config.txt The configuration of the topology file is mix/128_nodes_16_switch_topology.txt.

**Comment by jinsun-yoo** [comment]
@SallyChangLiu
Thank you for the sources! I have tried to register the tasks at the map at sim_send, but this did not fully solve the problem. It seems the discrepancy seems to be deeply ingrained somewhere in the code. Please give me a bit more time to dive into this issue. 

Thank you once more for bringing this to our attention!

**Comment by taekyounghan** [comment]
Hello @SallyChangLiu , I had the same problem as you, I also felt there is a problem with the code.
And I tried several combinations as below.
| configuration | workloads | physical_dims | Success | Fail |
|--------|--------|--------|--------|--------|
| Vanilla Resnet50_DataParallel.txt | "microAllReduce.txt", "Resnet50_DataParallel.txt" |   { 8, 4 }, { 8, 4 } |  | ✓ |
| Reduce Comm.size of Resnet50_DataParallel.txt | "microAllReduce.txt", "Resnet50_DataParallel.txt" | { 8, 4 }, { 8, 4 } | ✓ |  |
| Vanilla Resnet50_DataParallel.txt | "Resnet50_DataParallel.txt" | { 8, 4 } |  | ✓ |
| Vanilla Resnet50_DataParallel.txt | "microAllReduce.txt", "Resnet50_DataParallel.txt" |   { 8, 4 }, { 8, 2 } | ✓ |  |
| Vanilla Resnet50_DataParallel.txt | "Resnet50_DataParallel.txt"  | { 8, 2 } | ✓ |  |
| Vanilla Resnet50_DataParallel.txt | "Resnet50_DataParallel.txt" | {16} | ✓ |  | 
| Vanilla Resnet50_DataParallel.txt | "Resnet50_DataParallel.txt" | {32} | ✓ |  | 

![Untitled](https://github.com/astra-sim/astra-sim/assets/96406819/ea83fdc1-1315-4960-a64b-8d41efaa8460)

We can notice that simulation fails when
- size of weight gradient communication is large
- Inter-rack traffic appears

I'm also trying to solve this issue.

If I get to know more about the issue, I will share it with you.

**Comment by jinsun-yoo** [comment]
Hi all, here is an update on the current situation:
One of the refactoring items was to decouple the gluecode between ASTRA-sim and ns3. 
This means relocating the code surrounding `expeRecvHash`, etc. from the ns3 repo to the ASTRA-sim repo. 
Please refer to the below PRs: 
https://github.com/astra-sim/astra-sim/commit/f653a46699975feeeee5cac984e7ec9e90d7aff3
https://github.com/astra-sim/astra-network-ns3/pull/11

This job has just been completed, and I anticipate this will allow for a much more intuitive debugging of this issue.

**Comment by taekyounghan** [comment]
@jinsun-yoo @SallyChangLiu 
Hi all, I have some experience of this issue to share with you.

This issue was very difficult to identify and debug the cause.

In summary, under data-parallelism and hybrid-parallelism, the root cause of the problem is that each layer issues ig or wg before previous layers' communication is done (i.e., Non-blocking communication), **resulting in a lack of memory in the NS3 process** by **burstly adding RDMA queue-pairs** (i.e., network-level message, flow), which leads to simulation crash.

Here’s a several pages that includes memory comsumptionand NS3 crash and memory issue.

https://groups.google.com/g/ns-3-users/c/n2dCkSHaPmk

https://github.com/alibaba-edu/High-Precision-Congestion-Control/issues/9#issuecomment-658885976

https://stackoverflow.com/questions/53405949/ns3-sendstuff-cause-memory-increase

https://www.nsnam.org/docs/release/3.16/doxygen/classns3_1_1_object.html#ab259948b9de68d47d1bcd7d2b9841b1d

NS3 has its own memory management system through `Class::Object`. It seems that the simulation is automatically terminated through Disposal when a specific threshold is exceeded.

As a circumstantial evidence, I also checked `void QbbNetDevice::DoDispose()` is called which indirectly indicates simulation crashed by memory issue.

However, in DP, each layer has a different compute time, but weight gradient issue does not consider completing the communication of the previous layer (i.e., non-blocking communication)

This method is not logically problematic, but it can cause problems in this NS3 simulation.

This adds a queue-pair (which has size of each layer's weight gradient) to each node's `class RdmaHw` object almost simultaneously.

As far as I know, In real world, each NIC must perform a rate control operation in the form of a round robin for multiple queue-pairs.

However, the implementation of the corresponding NS-3 simulator does not appear to include such behavior.

While it is not impossible to process more than one queue pair with existing implementations, it seems difficult to process reliably by adding a queue pair with an initial rate of maximum bandwidth at the same time.

Evidence for this is as follows. In @SallyChangLiu 's execution environment, when performing ResNet

Please conduct following test individually

Case 1) Reduce the size of every weight_gradient to 65536B (Faster termination of each queue-pair)

Case 2) Increase the weight_gradient completion time to 100x (Less probability of overlapping when adding queue-pairs)

Case 3) Delayed Call of `void RdmaDriver::AddQueuePair` (Less probability of overlapping when adding queue-pairs)

For each case, the simulation was all performed normally.

In short, if the queue-pair that the node is transmitting is not terminated, and a new queue-pairs added burstly, a memory leak occurs somewhere.

Anyway, there seem to be three solutions to the above issue.

1. Intentionally delay the start of communication (ig and wg)
    1. In astra-sim/extern/network_backend/ns3-interface/simulation/scratch/third.cc , you could change `appCon.Start(NanoSeconds(0));` to `appCon.Start(NanoSeconds(700000));` then ResNet works.
    2. This heuristic method works but can lead to inefficient communication
2. Implement ns3 rdma that reliably controls multiple queue-pairs
    1. It looks like a lot of energy will go into this.
3. Use blocking-communication for DP and HP
    1. I added blocking commands to `void Workload::iterate_data_parallel()` ’s `Input_Gradient` Loop

```diff
else if (current_state == LoopState::Input_Gradient) {
    if (delay_loaded == false) {
      counter = layers[index]->get_input_grad_compute();
      delay_loaded = true;
    }
    if (counter > 0) {
      generator->try_register_event(
          this, EventType::Workload_Wait, NULL, counter);
      return;
    }
+if (!layers[index]->is_weight_grad_comm_finished_blocking()) { //Added by tk.han
+  return;
+}

    delay_loaded = false;
    index--;
    current_state = LoopState::Weight_Gradient;
    generator->register_event(this, EventType::General, NULL, 1);
    return;
  }
```

I think this method does not cause any communication inefficiency and can prevent memory problems in NS3. 
Also, I would like to ask the opinions of ASTRA-SIM developers about this method.

I'd appreciate it if you could reply or comment

Best Regards
Taekyoung

P.S. As far as I know, there seems to be no problem with the logic of `recvHash` and `expeRecvHash` that you were worried about.

**Comment by CavalryXD** [comment]
Hi, @taekyounghan @SallyChangLiu , I met a similar problem when I executed workload gpt3.txt.
The program runs at a given stage and then pauses but does not terminate.
and I also use MPI to accelerate the simulation speed.

My experiment setup is as follows:
system input:
> scheduling-policy: LIFO
endpoint-delay: 10
active-chunks-per-dimension: 1
preferred-dataset-splits: 4
boost-mode: 0
all-reduce-implementation: doubleBinaryTree_doubleBinaryTree
all-gather-implementation: ring_ring
reduce-scatter-implementation: ring_ring
all-to-all-implementation: direct_direct
collective-optimization: localBWAware

topology: 128_nodes_16_switch_topology.txt

I also try the all-reduce-implementation havlingDoubling_havingDoubling, the result is the same. If I change the system input's all-reduce-implementation to ring_ring, then the program runs normally.

And for excluding the NS3 memory problem, I set the topology to 16gpus and get same results(program pauses).

So the problem is the implementation of the collective algorithm(havingDoubling, ring, doubleBinaryTree) or the NS3 memory problem?

I look forward to hearing from your reply, thanks!

**Comment by jinsun-yoo** [comment]
Hi all, big apologies for the late news. 
Through much debugging we have found that the issue is more related to the System layer. 
(We did not observe a memory pressure failure in our machines)

I have created a new issue for this(#137) and linked a draft PR to the issue.
